### ISSUE TITLE
ROI

### ISSUE THREAD

**Issue by getcontrol** [AdivarekarBhumit/ID-Card-Segmentation#3]
Is there anyway to extract the bounding box coordinates of the output's ROI? Or crop it? 
![crop2](https://user-images.githubusercontent.com/9941190/69409045-104c2780-0cbd-11ea-9aea-dc2599a92e49.png)

**Comment by getcontrol** [comment]
I figured out how to do this.

**Comment by minamohamadii** [comment]
how you do it?
